name: Jekyll archive
on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Archive site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build site
      uses: actions/jekyll-build-pages@v1


    - name: Archive _site dir
      uses: actions/upload-artifact@v4
      with:
        name: columbiaviz-site
        path: _site
